development: &default
  session_secret: ''
  site_url: 'http://localhost:3000'
  site_title: '博客'
  site_motto: '.'
  site_description: '个人网站，发表个人原创的博客文章和学习笔记'
  site_author: ''
  show_certification: false
  show_me_url: '/blog/1/'
  blog_search_ping: false
  google_cse: ''
  weibo_api_key: ''
  weibo_api_secret: ''
  weibo_redirect_uri: 'http://localhost:3000/weibo_callback'
  weibo_uid: ''
  weibo_uid_verifier: ''
  gravatar: '/skins/data/100.png'
  weibo: ''
  github: ''
  email: ''
  certification: ''
  power_url: ''
  power_title: ''
  power_by_who: ''
test: 
  <<: *default

production:
  <<: *default
  site_url: ''
  blog_search_ping: false
